# Generated by Django 4.2.1 on 2023-08-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomaut', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_token',
            new_name='token',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='is_verified',
            new_name='verify',
        ),
    ]
