# Generated by Django 4.2.1 on 2023-08-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomaut', '0002_rename_email_token_profile_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forgetPasstoken',
            field=models.CharField(default=654645, max_length=200),
            preserve_default=False,
        ),
    ]
