# Generated by Django 4.2.1 on 2023-08-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomaut', '0003_profile_forgetpasstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fotgetPassLinkExpStatus',
            field=models.BooleanField(default=False),
        ),
    ]
