# Generated by Django 4.2.1 on 2023-08-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('desination', models.CharField(max_length=80)),
                ('socialid_linkidin', models.CharField(max_length=150)),
                ('socialid_twitter', models.CharField(max_length=150)),
                ('socialid_insta', models.CharField(max_length=150)),
                ('socialid_facebook', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='team/image')),
            ],
        ),
    ]
