# Generated by Django 4.2.1 on 2023-08-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='socialid_facebook',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='socialid_insta',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='socialid_linkidin',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='socialid_twitter',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
